Repository tagbase/tagbase-server, pull requests merged in 2023-04, with the labels that each got.

#214 ISSUE-211 fswatch needs to account for empty files created by sftp clients
  services/fswatch/post.sh
Labels: bug

#212 ISSUE-205 Is TestIngest PG_VERSION Class Variable required?
  .github/workflows/build.yml
  .spectral.yaml
  .thresholdrc
  openapi.yaml
  tagbase_server/tagbase_server/test/test_ingest.py
Labels: enhancement, openapi

#216 Fixes #215
  services/fswatch/post.sh
Labels: bug

#219 ISSUE-218 data_position.lon needs to be cast to integer in tagbase_materialized_views.sql
  services/postgis/tagbase_materialized_views.sql
Labels: bug

#223 ISSUE-220 data_position.lon needs to be cast to double in tagbase_materialized_views.sql
  services/postgis/tagbase_materialized_views.sql
Labels: bug

#225 ISSUE-224 metadata.tag_id incorrectly mimics metadata.submission_id
  tagbase_server/tagbase_server/utils/processing_utils.py
Labels: bug

#228 ISSUE-180 Implement DELETE admin tasks for tags and submissions
  .gitignore
  openapi.yaml
  services/postgis/tagbase_schema.sql
  tagbase_server/.openapi-generator/FILES
  tagbase_server/.openapi-generator/VERSION
  tagbase_server/README.md
  tagbase_server/tagbase_server/controllers/ingest_controller.py
  tagbase_server/tagbase_server/controllers/tags_controller.py
  tagbase_server/tagbase_server/models/__init__.py
  tagbase_server/tagbase_server/models/base_model_.py
  tagbase_server/tagbase_server/models/error.py
  tagbase_server/tagbase_server/models/error_container.py
  tagbase_server/tagbase_server/models/tag.py
  tagbase_server/tagbase_server/models/tag200.py
  tagbase_server/tagbase_server/models/tag_submission.py
  tagbase_server/tagbase_server/models/tags200.py
  tagbase_server/tagbase_server/openapi/openapi.yaml
  tagbase_server/tagbase_server/test/test_tags_controller.py
Labels: rest api, openapi
